### PR TITLE
Added interval to reduce cpu/ram usage 

### PR DESCRIPTION
**Pull request by p0ryae**
I had a spike in my CPU by using this.
This action is very unhealthy for long-term use and affects gaming performance.

I solved it by simply adding a 1s interval so it avoids checking on it every millisecond and there is a massive reduction in CPU usage.

### CODE REVIEW

**Comment by PrayagS** [comment]
Thanks for the contribution.

CPU usage has been an issue for a long time. The best solution is to ditch the constant DBus polling but that's how playerctl does it.

Thanks for adding this temporary fix.

**Review by PrayagS — APPROVED** [review]
LGTM

**Comment by p0ryae** [comment]
> Thanks for the contribution.
> 
> CPU usage has been an issue for a long time. The best solution is to ditch the constant DBus polling but that's how playerctl does it.
> 
> Thanks for adding this temporary fix.

Honestly think this should be a very great fix for most people out there - it reduced 10% cpu usage to 1% for me. Deal breaker for sure

**Comment by PrayagS** [comment]
> it reduced 10% cpu usage to 1% for me.

Ah, that's impressive. Seems like we got the easy way out. Thanks again for spotting this!

**Pull request merged**
