### PR TITLE
Fixed a misstypo in the README.md

### PR DESCRIPTION
**Pull request by p0ryae**

### CODE REVIEW

**Comment by PrayagS** [comment]
How is this a typo?

Polybar is supposed to call the scrolling script which in turn calls the Spotify script.

**Comment by p0ryae** [comment]
The file name you have uploaded in the GitHub repo is different from the file mentioned inside of the documentation.

**Comment by PrayagS** [comment]
https://github.com/PrayagS/polybar-spotify/blob/f8f492bc5619e661ef4cf90223887c2f19d8d5b7/README.md?plain=1#L42

This line calls the correct file ([scroll_spotify_status.sh](https://github.com/PrayagS/polybar-spotify/blob/master/scroll_spotify_status.sh)).

Your incoming change is calling [get_spotify_status.sh](https://github.com/PrayagS/polybar-spotify/blob/master/get_spotify_status.sh) which is not the intended way since we want the scroll script to grab this data and run it through the scroller first.

**Comment by p0ryae** [comment]
Ohhhh makes sense! Thanks for clarifying and sorry.

**Pull request closed without merging**
